apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weatherapp05
  name: weatherapp05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp05
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weatherapp05
    spec:
      containers:
      - image: drashyamalot/weather-app:latest
        name: weather-app
        resources:
         requests:
          cpu: "100m"
          memory: "128Mi"  # Minimum CPU requested by the pod
         limits:
          cpu: "200m"
          memory: "256Mi"

status: {}
